name: CI

on:
  merge_group:
  push:
    branches-ignore:
      - 'main'
      - '_bors*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  rust-checks:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/_reusable.rust.yml
    secrets:
      AWS_OIDC_ROLE: ${{ secrets.AWS_OIDC_ROLE }}

  open-api:
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v13
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Validate openapi
        run: just validate-openapi

  copyright:
    if: ${{ always() }}
    runs-on: hetzner-pm
    container:
      image: xaynetci/yellow:v13
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0

      - name: Check copyright
        run: .github/scripts/copyright.sh
